[project]
name = "ao-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aotools>=1.0.7",
    "matplotlib>=3.10.7",
    "numpy<2",
    "pydantic>=2.12.4",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "tqdm>=4.67.1",
]

[tool.uv]
package = true

